[workspace]
members = [
    "kizunalink",
    "kizuna-server",
]
resolver = "2"

[profile.dev]
opt-level = 1
debug = true
incremental = true
overflow-checks = false
lto = false
codegen-units = 256

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3
strip = true
