[package]
name = "kizuna-server"
version = "1.1.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
authors = [ "Nikhil",]
repository = "https://github.com/nikcodex/Kizunalink"

[dependencies]
subtle = "2.6"

[dependencies.kizunalink]
path = "../kizunalink"

[dependencies.base64]
workspace = true

[dependencies.bytes]
workspace = true

[dependencies.flume]
workspace = true

[dependencies.dashmap]
workspace = true

[dependencies.tracing]
workspace = true

[dependencies.futures]
workspace = true

[dependencies.async-trait]
workspace = true

[dependencies.serde_json]
workspace = true

[dependencies.byteorder]
workspace = true

[dependencies.regex]
workspace = true

[dependencies.ipnet]
workspace = true

[dependencies.rand]
workspace = true

[dependencies.toml]
workspace = true

[dependencies.parking_lot]
workspace = true

[dependencies.thiserror]
workspace = true

[dependencies.sysinfo]
workspace = true

[dependencies.prometheus]
workspace = true

[dependencies.perf_monitor]
workspace = true

[dependencies.tracing-subscriber]
workspace = true

[dependencies.serde]
workspace = true

[dependencies.time]
workspace = true

[dependencies.uuid]
workspace = true

[dependencies.reqwest]
workspace = true

[dependencies.tokio]
workspace = true

[dependencies.axum]
workspace = true

[dependencies.tower-http]
workspace = true
