.nh
.TH "GH-CACHE-LIST" "1" "Jul 2023" "GitHub CLI 2.32.1" "GitHub CLI manual"

.SH NAME
.PP
gh-cache-list - List Github Actions caches


.SH SYNOPSIS
.PP
\fB\fCgh cache list [flags]\fR


.SH OPTIONS
.TP
\fB\fC-L\fR, \fB\fC--limit\fR \fB\fC<int>\fR
Maximum number of caches to fetch

.TP
\fB\fC-O\fR, \fB\fC--order\fR \fB\fC<string>\fR
Order of caches returned: {asc|desc}

.TP
\fB\fC-S\fR, \fB\fC--sort\fR \fB\fC<string>\fR
Sort fetched caches: {created_at|last_accessed_at|size_in_bytes}


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH EXAMPLE
.PP
.RS

.nf
# List caches for current repository
$ gh cache list

# List caches for specific repository
$ gh cache list --repo cli/cli

# List caches sorted by least recently accessed
$ gh cache list --sort last_accessed_at --order asc


.fi
.RE


.SH SEE ALSO
.PP
\fB\fCgh-cache(1)\fR
